version: '3.8'
services:
  nodejs:
    image: node:${NODE_VERSION}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: bash -c "npm install depcheck --location=global  --force && sleep infinity"
    tty: true
    working_dir: '/var/www/html'
    volumes:
      - '../.:/var/www/html'
    networks:
      - devcontainer-cms-barbu-cc_strapi
    container_name: ${APP_NAME}_nodejs

networks:
  devcontainer-cms-barbu-cc_strapi:
    external: true