version: '3.8'
services:
  nodejs:
    image: node:${NODE_VERSION}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: bash -c "npx depcheck && sleep infinity"
    tty: true
    working_dir: '/var/www/html'
    volumes:
      - '../.:/var/www/html'
    networks:
      - barbu-cc
    container_name: ${APP_NAME}_nodejs

networks:
  barbu-cc:
    external: true