version: '3.8'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_VERSION: ${NODE_VERSION}
      NODE_ENV: ${NODE_ENV}
      DOPPLER_TOKEN: ${DOPPLER_TOKEN_API}
    command: bash -c "npm install depcheck --location=global  --force && sleep infinity"
    tty: true
    working_dir: '/var/www/html'
    volumes:
      - '../.:/var/www/html'
    networks:
      - barbu-cc
    container_name: ${APP_NAME}_nodejs

networks:
  barbu-cc:
    external: true